### ISSUE TITLE
Which components can handle SSR?

### ISSUE THREAD

**Issue by luminarious** [Kong/kongponents#2263]
Hey! Nuxt projects tend to heavily rely on SSR and I am researching UI kits for a project. Kongponents overall seem to have very nice docs and a nice API.

- Have you audited which components currently support SSR? For example KTable currently doesn't, examples in the docs render on client-side only.
- Have you considered adding this information to docs?

**Comment by adamdehaven** [comment]
Kongponents were originally designed for use within client-side rendered Vue apps. With the latest `9.x` release, most components are now SSR-compatible, with a few exceptions. 

Primarily, `KTable` and `KCatalog` are not SSR-compatible, partially due to their internal data fetching.

- As a replacement for KCatalog, you could use your own grid of `KCard` components.
- For `KTable`, we plan on implementing a simpler data table component that relies on external data fetching (planned date TBD).

**Comment by adamdehaven** [comment]
> a purely presentational table

This is the plan; the table just outputs the data it's given (and/or slotted)
